### PR TITLE
fix(devices): Reinstate device commands, with performance fixes.

### LINKED ISSUE #384: Reinstate the upsertAvailableCommands stored procedure
We need to revert this abomination:

https://github.com/mozilla/fxa-auth-db-mysql/commit/06554f5599fb167bcdf79c8586f2d7c9ab87643e

...and replace it with a proper fix.

By "proper fix", I mean something that doesn't cause lock contention when the session-related stored procedures try to join with the `deviceCommands` table, which was the cause of a major outage in prod this weekend.

### PR DESCRIPTION
**Pull request by rfk**
Fixes #384, based on analysis from https://github.com/mozilla/fxa-auth-db-mysql/issues/384#issuecomment-414565389.

I believe we plan to do this as a point release of train-119, but since there aren't any other commits on master yet, perhaps it's simpler to land it on master and then cut the point release from there?

@philbooth @jrgm r?

### CODE REVIEW

**Comment by rfk** [comment]
The other piece of the puzzle here, will be adding a simple way to pref this behaviour off if it is still giving us trouble in production.  Rather than doing it here, I propose that we extend the "pushbox enabled" feature-flag in the auth-server so that it can pref the entire device-commands infra on and off.

File: lib/db/schema/patch-084-085.sql [hunk 1]
```diff
@@ -0,0 +1,204 @@
...
+  INNER JOIN sessionTokens AS s
+    ON d.sessionTokenId = s.tokenId
+  LEFT JOIN (
+    deviceCommands AS dc
+    INNER JOIN deviceCommandIdentifiers AS ci
+      ON ci.commandId = dc.commandId
+  ) ON (dc.uid = d.uid AND dc.deviceId = d.id)
+  WHERE d.uid = uidArg
+  -- For easy flattening, ensure rows are ordered by device id.
+  ORDER BY 1, 2;
```
Comment (vladikoff) [inline lib/db/schema/patch-084-085.sql]: image

File: lib/db/schema/patch-084-085.sql [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+  FROM devices AS d
+  INNER JOIN sessionTokens AS s
+    ON d.sessionTokenId = s.tokenId
+  LEFT JOIN (
+    deviceCommands AS dc
+    INNER JOIN deviceCommandIdentifiers AS ci
+      ON ci.commandId = dc.commandId
+  ) ON (dc.uid = d.uid AND dc.deviceId = d.id)
+  WHERE d.uid = uidArg
+  AND d.id = idArg;
```
Comment (vladikoff) [inline lib/db/schema/patch-084-085.sql]: ⚠️ Full Index Scan

image

File: lib/db/schema/patch-084-085.sql [hunk 3]
```diff
@@ -0,0 +1,204 @@
...
+  LEFT JOIN devices AS d
+    ON (t.tokenId = d.sessionTokenId AND t.uid = d.uid)
+  LEFT JOIN (
+    deviceCommands AS dc
+    INNER JOIN deviceCommandIdentifiers AS ci
+      ON ci.commandId = dc.commandId
+  ) ON (dc.uid = d.uid AND dc.deviceId = d.id)
+  LEFT JOIN unverifiedTokens AS ut
+    ON t.tokenId = ut.tokenId
+  WHERE t.tokenId = tokenIdArg;
```
Comment (vladikoff) [inline lib/db/schema/patch-084-085.sql]: image

File: lib/db/schema/patch-084-085.sql [hunk 4]
```diff
@@ -0,0 +1,204 @@
...
+  FROM sessionTokens AS t
+  LEFT JOIN devices AS d
+    ON (t.tokenId = d.sessionTokenId AND t.uid = d.uid)
+  LEFT JOIN (
+    deviceCommands AS dc
+    INNER JOIN deviceCommandIdentifiers AS ci
+      ON ci.commandId = dc.commandId
+  ) ON (dc.uid = d.uid AND dc.deviceId = d.id)
+  WHERE t.uid = uidArg
+  ORDER BY 1;
```
Comment (vladikoff) [inline lib/db/schema/patch-084-085.sql]: ⚠️ Full Index, Full Table Scan 

image

File: lib/db/schema/patch-084-085.sql (hunk 2 above)
Comment (rfk) [reply lib/db/schema/patch-084-085.sql]: Interesting.  MySQL appears to be choosing this query plan because it knows that the `deviceCommandIdentifiers` table is very small, so the full index scan on `ci` is cheap.  If it add a couple more rows to the `deviceCommandIdentifiers` table then it changes its plan to look up in `dc` before `ci`, which is what we'd expect.

File: lib/db/schema/patch-084-085.sql (hunk 4 above)
Comment (rfk) [reply lib/db/schema/patch-084-085.sql]: filesort O_O

**Comment by rfk** [comment]
@vladikoff I added some `FORCE INDEX` hints to help the query planner make good choices even when the tables are small, could you please take another look?

File: lib/db/schema/patch-084-085.sql [hunk 5]
```diff
@@ -0,0 +1,209 @@
...
+  FROM devices AS d
+  INNER JOIN sessionTokens AS s
+    ON d.sessionTokenId = s.tokenId
+  LEFT JOIN (
+    deviceCommands AS dc FORCE INDEX (PRIMARY)
+    INNER JOIN deviceCommandIdentifiers AS ci FORCE INDEX (PRIMARY)
+      ON ci.commandId = dc.commandId
+  ) ON (dc.uid = d.uid AND dc.deviceId = d.id)
+  WHERE d.uid = uidArg
+  AND d.id = idArg;
```
Comment (vladikoff) [inline lib/db/schema/patch-084-085.sql]: image

File: lib/db/schema/patch-084-085.sql [hunk 6]
```diff
@@ -0,0 +1,209 @@
...
+    dc.commandData
+  FROM unverifiedTokens AS u
+  INNER JOIN devices AS d
+    ON (u.tokenId = d.sessionTokenId AND u.uid = d.uid)
+  LEFT JOIN (
+    deviceCommands AS dc FORCE INDEX (PRIMARY)
+    INNER JOIN deviceCommandIdentifiers AS ci FORCE INDEX (PRIMARY)
+      ON ci.commandId = dc.commandId
+  ) ON (dc.uid = d.uid AND dc.deviceId = d.id)
+  WHERE u.uid = inUid AND u.tokenVerificationId = inTokenVerificationId;
```
Comment (vladikoff) [inline lib/db/schema/patch-084-085.sql]: image

File: lib/db/schema/patch-084-085.sql [hunk 7]
```diff
@@ -0,0 +1,209 @@
...
+  FROM sessionTokens AS t
+  LEFT JOIN devices AS d
+    ON (t.tokenId = d.sessionTokenId AND t.uid = d.uid)
+  LEFT JOIN (
+    deviceCommands AS dc FORCE INDEX (PRIMARY)
+    INNER JOIN deviceCommandIdentifiers AS ci FORCE INDEX (PRIMARY)
+      ON ci.commandId = dc.commandId
+  ) ON (dc.uid = d.uid AND dc.deviceId = d.id)
+  WHERE t.uid = uidArg
+  ORDER BY 1;
```
Comment (vladikoff) [inline lib/db/schema/patch-084-085.sql]: image
