### PR TITLE
fix(deps): update restify and mysql

### LINKED ISSUE #348: Fix NSP 602
Ref https://github.com/mozilla/fxa-auth-db-mysql/pull/347/files#diff-03cb303c8d3085901cf5a9214888ad1dR4

### LINKED ISSUE #349: Fix NSP 598
Ref: https://github.com/mozilla/fxa-auth-db-mysql/pull/347/files#diff-03cb303c8d3085901cf5a9214888ad1dR6

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #348 
Fixes #349

### CODE REVIEW

File: db-server/index.js [hunk 1]
```diff
@@ -3,10 +3,10 @@
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 
 var restify = require('restify')
-var safeJsonFormatter = require('restify-safe-json-formatter')
 var bufferize = require('./lib/bufferize')
 var version = require('../package.json').version
 var errors = require('./lib/error')
+const safeJsonFormatter = require('./lib/safeJsonFormatter')
```
Comment (vbudhram) [inline db-server/index.js]: Since the `safeJsonFormatter` lib wasn't too big, opted to pull this into our repo. The new version of restify doesn't accept a `cb` for formatters.

File: db-server/index.js [hunk 2]
```diff
@@ -266,6 +267,13 @@ function createServer(db) {
       res.send(result.map(bufferize.unbuffer))
     }
     else {
+
+      // When performing a `HEAD` request, the content type is not
+      // set, manually set to application/json
+      if (req.method === 'HEAD') {
```
Comment (vbudhram) [inline db-server/index.js]: Not sure if this is a bug or expected for `HEAD` requests. Only the [/emailRecord/:id](https://github.com/mozilla/fxa-auth-db-mysql/blob/536d413e441b08ffb33ae2073c906f339744d0fa/db-server/index.js#L157) uses `HEAD`. I could modify the test case or add this clause for backwards compat.

File: db-server/test/client-then.js [hunk 3]
```diff
@@ -1,7 +1,7 @@
 /* Any copyright is dedicated to the Public Domain.
  * http://creativecommons.org/publicdomain/zero/1.0/ */
 
-var restify = require('restify')
+const clients = require('restify-clients')
```
Comment (vbudhram) [inline db-server/test/client-then.js]: In the new version, clients were moved to their own package.

**Comment by vbudhram** [comment]
@mozilla/fxa-devs r?

File: db-server/index.js (hunk 1 above)
Comment (rfk) [reply db-server/index.js]: Just adding context, this is vendored in from https://github.com/g-k/restify-safe-json-formatter/blob/master/index.js and is already Mozilla code written by g-k (so we'll pulling in code Mozilla already owns, not some third-party dep)

File: package.json [hunk 4]
```diff
@@ -34,12 +34,12 @@
...
     "mozlog": "2.1.0",
-    "mysql": "2.13.0",
+    "mysql": "2.15.0",
     "mysql-patcher": "0.7.0",
     "newrelic": "4.1.0",
     "raven": "2.3.0",
     "request": "2.83.0",
-    "restify": "4.3.0",
+    "restify": "7.1.1",
     "restify-safe-json-formatter": "0.2.0",
```
Comment (rfk) [inline package.json]: Since it's been inlined, we should remove it from `package.json`, right?
