### PR TITLE
fix(account): don't use `LOWER(uid)` in account query, update `accountRecord`

### LINKED ISSUE #438: The `account_5` procedure uses `LOWER(inUid)` in its `WHERE clause.
The `account_5` stored procedure does the following:

```
   SELECT ...lots of columns... FROM accounts a WHERE a.uid = LOWER(inUid)        
```

Do we really need `LOWER` in there, or is this copypasta from a previous procedure that was dealing with emails?  AFAICT `LOWER` does nothing when applied to `BINARY` strings, which the `inUid` argument is declared as.

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #438 
Connects to https://github.com/mozilla/fxa-auth-db-mysql/issues/440

Opted to pull these two issues into one migration since they were both fairly small and not to introduce too much headache with merge conflicts for https://github.com/mozilla/fxa-auth-db-mysql/pull/436.

First commit:
Removes the `LOWER(uid)` from the `account_` stored procedure since it doesn't really change the query.

Second commit:
From https://github.com/mozilla/fxa-auth-db-mysql/issues/440, it specifies the charact set for `inEmail` as utf8 for the `accountRecord_` procedure. It also re enables coalescing in SQL rather than in code.

### CODE REVIEW

File: lib/db/schema/patch-091-092.sql [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+        a.emailCode,
+        a.kA,
+        a.wrapWrapKb,
+        a.verifierVersion,
+        a.authSalt,
+        a.verifierSetAt,
+        a.createdAt,
+        a.locale,
+        a.lockedAt,
+        COALESCE(a.verifierSetAt, a.createdAt) AS profileChangedAt
```
Comment (philbooth) [inline lib/db/schema/patch-091-092.sql]: Isn't this the problematic `COALESCE` mentioned in the comment above? We don't want to reintroduce it do we?

Comment (vbudhram) [reply lib/db/schema/patch-091-092.sql]: I believe the problem was with `accountRecord_*` procedure. That has been updated below so that it hopefully doesn't cause the unexpected behavior.

Comment (philbooth) [reply lib/db/schema/patch-091-092.sql]: Got it, wrong `COALESCE`. And so the `CHARACTER SET utf8 COLLATE utf8_bin` is the fix for that, hence the comment. Makes sense now, sorry!
