### PR TITLE
fix(reminders): adjust mysql procedures

### LINKED ISSUE #196: Some thoughts on verification reminder queries
I had a bit of a look at the way we're dealing with verification reminders, with an eye to better understanding performance and interaction with replication etc.  Some thoughts and observations for later followup below - sorry they're a bit free-form, but I wanted to capture them before I head off on PTO.

---

The table schema is:

```
CREATE TABLE IF NOT EXISTS verificationReminders (
  id BINARY(32) PRIMARY KEY,
  uid BINARY(16) NOT NULL,
  type VARCHAR(255) NOT NULL,
  createdAt BIGINT SIGNED NOT NULL,
  INDEX reminder_createdAt (createdAt)
) ENGINE=InnoDB;
```

It's not obvious to me whether we use the `id` field for anything.  Do we?  If not, perhaps we should have `uid, type` as a composite primary key.  This would avoid us accidentally creating duplicate reminder entries, and would also help with the next issue below.

----

We delete verification reminders by doing:

```
DELETE FROM verificationReminders WHERE uid = reminderUid AND type = reminderType;
```

But we don't have an index on those columns, and `EXPLAIN` confirms that this query will do a full table scan.

We should add an index on (uid, type), either by making it the primary key, or using a secondary index.

I also wonder whether we should delete the verification reminders as part of the `verifyEmail` stored procedure rather than as a separate call to the DB.  We don't need to call this procedure when fetching the reminders, see below.

----

We do several things in `fetchVerificationReminders_1` that are not replication-friendly, including asking MySQL for the current time, and using `SELECT .. FOR UPDATE`, and doing `LIMIT` without an `ORDER BY`.

I *think* MySQL replication handles timestamps sanely, but it might simplify the query logic if we passed in the timestamp explicitly.

We may be able to use `GET_LOCK` to simplify the query some.  It's also not safe for replication, but may be simpler for MySQL to deal with overall.  I'm thinking something like:

```
CREATE PROCEDURE `fetchVerificationReminders_2` (
    IN currentTime BIGINT SIGNED,
    IN reminderType VARCHAR(255),
    IN reminderTime BIGINT SIGNED,
    IN reminderTimeOutdated BIGINT SIGNED,
    IN reminderLimit INTEGER
)
BEGIN
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    DO RELEASE_LOCK('fxa-auth-server.verification-reminders-lock');
    ROLLBACK;
    RESIGNAL;
  END;

  START TRANSACTION;

  SELECT @lockAcquired:=GET_LOCK('fxa-auth-server.verification-reminders-lock', 1)
  AS lockAcquired;

  IF @lockAcquired THEN

    DROP TEMPORARY TABLE IF EXISTS reminderResults;

    -- Select these straight into the temporary table
    -- rather than using a cursor.  Use ORDER BY to
    -- ensure the query is deterministic.

    CREATE TEMPORARY TABLE reminderResults AS 
      SELECT uid, type
      FROM verificationReminders
      -- Since we want to order by `createdAt`, we have to rearrange
      -- the `WHERE` clauses so `createdAt` is positive rather than negated.
      WHERE  createdAt < currentTime - reminderTime
      AND createdAt > currentTime - reminderTimeOutdated
      AND type = reminderType
      ORDER BY createdAt, uid, type
      LIMIT reminderLimit;
    
    -- Because the query is deterministic we can delete
    -- all the selected items at once, rather than calling
    -- deleteVerificationReminder()

    DELETE FROM verificationReminders 
      WHERE  createdAt < currentTime - reminderTime
      AND createdAt > currentTime - reminderTimeOutdated
      AND type = reminderType
      ORDER BY createdAt, uid, type
      LIMIT reminderLimit;

    -- Clean up outdated reminders.
    -- `EXPLAIN` says this wasn't actually using the index on `createdAt` because of
    -- the way the `WHERE` clause was structured, rearranging it to put `createdAt`
    -- by itself on one side of the comparison allows it to use the index.

    DELETE FROM
      verificationReminders
    WHERE
      createdAt < currentTime - reminderTimeOutdated
    AND
      type = reminderType;

    -- Return the result
    SELECT * FROM reminderResults;

    DO RELEASE_LOCK('fxa-auth-server.verification-reminders-lock');

  END IF;
  COMMIT;
```

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #196

### CODE REVIEW

File: lib/db/schema/patch-039-040.sql [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+  DECLARE EXIT HANDLER FOR SQLEXCEPTION
+  BEGIN
+    DO RELEASE_LOCK('fxa-auth-server.verification-reminders-lock');
+    ROLLBACK;
+    RESIGNAL;
+  END;
+
+  START TRANSACTION;
+
+  DO @lockAcquired:=GET_LOCK('fxa-auth-server.verification-reminders-lock', 1) AS lockAcquired;
```
Comment (vladikoff) [inline lib/db/schema/patch-039-040.sql]: @rfk Only mysql 5.7+ seems to support this `DO` syntax. any ideas?

Comment (vladikoff) [inline lib/db/schema/patch-039-040.sql]: In 5.6+ I get

```
"Fields":{"err":"Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS lockAcquired;\n\n  IF @lockAcquired THEN\n    DROP TEMPORARY TABLE IF EXISTS rem' at line 14"}}
```

Comment (rfk) [inline lib/db/schema/patch-039-040.sql]: Do we need the `AS lockAcquired` part if we're assigning to varialbe with `@lockAcquired:=`?  I don't recall the precise details of the semantics here, will try to poke at this a little tomorrow.

File: lib/db/schema/patch-039-040.sql [hunk 2]
```diff
@@ -0,0 +1,66 @@
+ALTER TABLE `verificationReminders` DROP PRIMARY KEY, ADD PRIMARY KEY (`uid`, `type`);
```
Comment (rfk) [inline lib/db/schema/patch-039-040.sql]: I'm guessing that we can't use `ALGORITHM = INPLACE, LOCK = NONE` on this `ALTER TABLE`, meaning that it will block any other attempts to write into this table.  Does locking this table matter in production?  If e.g. we're not writing anything into the table yet in production then it's probably OK, but may be worth a short comment to that effect in the migration here.

Comment (vladikoff) [inline lib/db/schema/patch-039-040.sql]: I'll just recreate the table, so shouldn't be an issue as far as I understand

**Comment by vladikoff** [comment]
> It'd be good to get the output of EXPLAIN

```
mysql> EXPLAIN SELECT uid, type FROM verificationReminders WHERE (ROUND(UNIX_TIMESTAMP(CURTIME(4)) * 1000) - 123) > createdAt AND type = 'first';      
+----+-------------+-----------------------+-------+--------------------+--------------------+---------+------+------+--------------------------+
| id | select_type | table                 | type  | possible_keys      | key                | key_len | ref  | rows | Extra                    |
+----+-------------+-----------------------+-------+--------------------+--------------------+---------+------+------+--------------------------+
|  1 | SIMPLE      | verificationReminders | index | reminder_createdAt | reminder_createdAt | 8       | NULL |    2 | Using where; Using index |
+----+-------------+-----------------------+-------+--------------------+--------------------+---------+------+------+--------------------------+
1 row in set (0.00 sec)

mysql>  EXPLAIN SELECT uid, type FROM verificationReminders WHERE type = 'first';      
+----+-------------+-----------------------+-------+---------------+--------------------+---------+------+------+--------------------------+
| id | select_type | table                 | type  | possible_keys | key                | key_len | ref  | rows | Extra                    |
+----+-------------+-----------------------+-------+---------------+--------------------+---------+------+------+--------------------------+
|  1 | SIMPLE      | verificationReminders | index | NULL          | reminder_createdAt | 8       | NULL |    2 | Using where; Using index |
+----+-------------+-----------------------+-------+---------------+--------------------+---------+------+------+--------------------------+
1 row in set (0.00 sec)

mysql> 
mysql>  EXPLAIN SELECT uid, type FROM verificationReminders ORDER BY uid, type; 
+----+-------------+-----------------------+-------+---------------+---------+---------+------+------+-------------+
| id | select_type | table                 | type  | possible_keys | key     | key_len | ref  | rows | Extra       |
+----+-------------+-----------------------+-------+---------------+---------+---------+------+------+-------------+
|  1 | SIMPLE      | verificationReminders | index | NULL          | PRIMARY | 783     | NULL |    2 | Using index |
+----+-------------+-----------------------+-------+---------------+---------+---------+------+------+-------------+
1 row in set (0.00 sec)

mysql> 

```

**Comment by vladikoff** [comment]
@rfk final r?

File: lib/db/schema/patch-039-040.sql [hunk 3]
```diff
@@ -0,0 +1,97 @@
+-- Drop the old reminders table, it was not functioning correctly
+DROP TABLE IF EXISTS `verificationReminders`;
```
Comment (rfk) [inline lib/db/schema/patch-039-040.sql]: @jrgm can you please confirm that reminders are disabled in production, so dropping this table will not cause account creations to error out when attempting to add a reminder?  I'm pretty sure that's the case, but I want to be *very* sure.

Comment (vladikoff) [inline lib/db/schema/patch-039-040.sql]: I made a note for this in the deploy doc
