### PR TITLE
fix(query): remove `ROW_COUNT()` from remaining procedures

### LINKED ISSUE #411: Remove use of ROW_COUNT() and forbid its return
In [Bug 1499819](https://bugzilla.mozilla.org/show_bug.cgi?id=1499819) we identified use of the `ROW_COUNT()` function as causing significant db replication lag in production.  In #410 we modified two of our more frequently-called stored procedures to remove it, and that seems to have fixed the db lag issue.

For completeness, we should:

* Remove use of `ROW_COUNT()` from other stored procedures, even if they're only called occasionally.
* Update out mysql linting/CI logic to detect future attempts to use `ROW_COUNT()`, and forbid them.

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #411 

This PR removes the use of `ROW_COUNT()` from our remaining procedures. Below is a summary of our use of `ROW_COUNT()` and when they were fixed.

- setPrimaryEmail
  - Fixed in setPrimaryEmail_4 (this PR)
- consumeRecoveryCode
  - Fixed in consumeRecoveryCode_3 (this PR)
- verifyTokensWithMethod
  - Fixed in verifyTokensWithMethod_3
- deleteEmail
  - Fixed in deleteEmail_2
- verifyTokenCode
  - Fixed in verifyTokenCode_2
- verifyEmail
  - Fixed in verifyEmail_4

### CODE REVIEW

**Comment by vbudhram** [comment]
@mozilla/fxa-devs r?

File: lib/db/mysql.js [hunk 1]
```diff
@@ -916,15 +916,12 @@ module.exports = function (log, error) {
...
+  var SET_PRIMARY_EMAIL = 'CALL setPrimaryEmail_4(?, ?)'
   MySql.prototype.setPrimaryEmail = function (uid, email) {
-    return this.write(
-      SET_PRIMARY_EMAIL,
-      [
-        uid,
-        email
-      ]
-    )
+    return this.read(SET_PRIMARY_EMAIL, [uid, email])
```
Comment (rfk) [inline lib/db/mysql.js]: Why did this change from `this.write()` to `this.read()`?

File: lib/db/schema/patch-092-093.sql [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+BEGIN
+  DECLARE EXIT HANDLER FOR SQLEXCEPTION
+  BEGIN
+    ROLLBACK;
+    RESIGNAL;
+  END;
+
+  START TRANSACTION;
+     UPDATE emails SET isPrimary = false WHERE uid = inUid AND isPrimary = true;
+     UPDATE emails SET isPrimary = true WHERE uid = inUid AND isPrimary = false AND normalizedEmail = inNormalizedEmail;
```
Comment (rfk) [inline lib/db/schema/patch-092-093.sql]: The previous version of this procedure used `ROW_COUNT` to check whether the user actually owns `inNormalizedEmail`, to avoid accidentally leaving them in a state where they do now have a primary emil address:

```
IF @updateCount = 0 THEN
  SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = 1062, MESSAGE_TEXT = 'Can not change email. Could not find email.';
END IF;
```

Does the responsibility for this check now live somewhere else?

File: lib/db/schema/patch-092-093.sql [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+  BEGIN
+    ROLLBACK;
+    RESIGNAL;
+  END;
+
+  START TRANSACTION;
+
+  DELETE FROM `recoveryCodes` WHERE `uid` = `uidArg` AND `codeHash` = `codeHashArg`;
+
+  SELECT COUNT(*) AS count FROM `recoveryCodes` WHERE `uid` = `uidArg`;
```
Comment (rfk) [inline lib/db/schema/patch-092-093.sql]: The previous version of this procedure used `ROW_COUNT` to check whether we actually found the given code on the user's account:

```
SELECT ROW_COUNT() INTO @deletedCount;
IF @deletedCount = 0 THEN
   SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = 1643, MESSAGE_TEXT = 'Unknown recovery code.';
END IF;
```

Does the responsibility for this check now live somewhere else?

Comment (vbudhram) [reply lib/db/schema/patch-092-093.sql]: @rfk The responsibility for this check actually lives here now, https://github.com/mozilla/fxa-auth-db-mysql/pull/445/files#diff-551d684cf1c1a288045d0e9dbce3569eL1531. I believe when we started storing scrypted values of the recovery code, this procedure wasn't updated.

File: lib/db/schema/patch-092-093.sql (hunk 2 above)
Comment (vbudhram) [reply lib/db/schema/patch-092-093.sql]: @rfk The responsibility of this check lives on the auth-server, https://github.com/mozilla/fxa-auth-server/blob/42d165eccc1ab0694e9cc46ab40362a7aa8e393d/lib/routes/emails.js#L759. I'll add some additional comments to better document these.

File: lib/db/mysql.js (hunk 1 above)
Comment (vbudhram) [reply lib/db/mysql.js]: Ah, I might have missed this when testing different approaches. I'll update to `this.write()`.

File: lib/db/schema/patch-092-093.sql (hunk 2 above)
Comment (rfk) [reply lib/db/schema/patch-092-093.sql]: Aha, thanks!

There's a pedantic part of me that doesn't quite feel comfortable that this check lives outside of the transaction boundary.  You can imagine a (highly unlikely) sequence of events where concurrent calls to `deleteEmail` and `setPrimaryEmail` result in an account with no primary email address.  Such calls shouldn't happen concurrently in practice, but "shouldn't" is not the same as "can't"...

Comment (rfk) [reply lib/db/schema/patch-092-093.sql]: Changing primary email happens infrequently enough that I feel like we could spare an additional db lookup (say, to confirm that the user owns the given email address at the beginning of the procedure) in order to guard against producing a bad db state.

**Comment by vbudhram** [comment]
@rfk Updated with your recommendations, r?

**Comment by vladikoff** [comment]
from mtg: we wanna try to get it into this train

File: lib/db/mysql.js [hunk 4]
```diff
@@ -916,15 +916,27 @@ module.exports = function (log, error) {
...
-      [
-        uid,
-        email
-      ]
-    )
+    return this.getSecondaryEmail(email)
+      .then((emailRecord) => {
+        if (emailRecord.uid.toString('utf8') !== uid.toString('utf8')) {
+          throw error.cannotSetUnownedPrimaryEmail()
+        }
```
Comment (rfk) [inline lib/db/mysql.js]: This is still doing the check outside of a transaction boundary, which means there's a (very small, but non-zero) chance that we could put the db in a bad state.  We could use `this.transaction` here to manage the transaction in code (see the definition of `writeMultiple` for an example).  Or we could find another way to do the check inside the transaction in the stored procedure, perhaps something like:

```
START TRANSACTION;
  SELECT normalizedEmail INTO @foundEmail FROM emails WHERE uid = inUid AND normalizedEmail = inNormalizedEmail AND isVerified;
  IF @foundEmail IS NULL THEN
   SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = 1062, MESSAGE_TEXT = 'Can not change email. Could not find email.';
  END IF;

  UPDATE emails SET isPrimary = false WHERE uid = inUid AND isPrimary = true;
  UPDATE emails SET isPrimary = true WHERE uid = inUid AND normalizedEmail = inNormalizedEmail;
COMMIT;
```

**Comment by vbudhram** [comment]
@rfk Added the checks inside of transaction, r? Pulling shipit off since I don't think there is an urgency for getting onto this train.

File: lib/db/schema/patch-092-093.sql [hunk 5]
```diff
@@ -0,0 +1,59 @@
+-- This migration removes the use of `ROW_COUNT()` on the last
+-- remaining procedures.
+SET NAMES utf8mb4 COLLATE utf8mb4_bin;
+
+CALL assertPatchLevel('92');
+
+-- Updated to not use `ROW_COUNT()`. The previous procedure used row count to ensure that
+-- the uid actually owned the email specified. This sanity check is performed in the `db.setPrimaryEmail` now.
```
Comment (rfk) [inline lib/db/schema/patch-092-093.sql]: nit: the comment about there the check is performed seems out-of-date now?

File: lib/db/mysql.js [hunk 6]
```diff
@@ -916,15 +916,23 @@ module.exports = function (log, error) {
...
-        uid,
-        email
-      ]
-    )
+    return this.write(SET_PRIMARY_EMAIL, [uid, email])
+      .then(() => {
+        return {}
+      })
+      .catch(err => {
+        if (err.errno === error.duplicate().errno) {
```
Comment (rfk) [inline lib/db/mysql.js]: Looks like we could benefit from the auth-server's approach of giving our errono's easy named constants, but that's beyond the scope of this PR :-)

Comment (vbudhram) [reply lib/db/mysql.js]: Good idea! Created https://github.com/mozilla/fxa-auth-db-mysql/issues/447, so we don't lose track.
