### PR TITLE
fix(recovery): hash recovery key id

### LINKED ISSUE #366: Hash recovery key ids for storage, to ensure constant-time lookup
For codes that can be used to look up potentially-sensitive information, we generally store them in the db by hash rather than in raw form, e.g:

  https://github.com/mozilla/fxa-auth-db-mysql/blob/master/lib/db/mysql.js#L1379

Part of the idea here is to guard against possible timing attacks in the DB lookup, which would allow guessing the code one character at a time.

Recovery keys currently do not get this treatment, and the recoveryKeyId is stored in the db in raw form.  For both consistency and completeness, we should probably give recoveryKeyIds the same treatment as, say, signin codes and unblock codes.

I don't think it's super urgent, but we should resolve it before preffing the feature on in production.

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #366 

~~WIP, need to confirm how many users enabled recovery key in production.~~

Confirmed that no one has enabled this in production yet.

### CODE REVIEW

**Comment by vbudhram** [comment]
@mozilla/fxa-devs r?

File: db-server/test/backend/db_tests.js [hunk 1]
```diff
@@ -2284,7 +2285,8 @@ module.exports = function (config, DB) {
         return db.getRecoveryKey(options)
           .then((res) => {
             assert.equal(res.recoveryData, data.recoveryData, 'recovery data set')
-            assert.equal(res.recoveryKeyId.toString('hex'), data.recoveryKeyId.toString('hex'), 'recovery data set')
+            const recoveryKeyId = util.createHash(data.recoveryKeyId)
```
Comment (rfk) [inline db-server/test/backend/db_tests.js]: It's super nit-picky, but I think this test would read clearer if the variable here were named `recoveryKeyIdHash` rather than `recoveryKeyId` - for a moment I interpreted the assertion below as saying "the recovery key id hash is equal to the recovery key id" which seemed very confusing :-)

File: lib/db/schema/patch-085-086.sql [hunk 2]
```diff
@@ -0,0 +1,45 @@
+SET NAMES utf8mb4 COLLATE utf8mb4_bin;
+
+CALL assertPatchLevel('85');
+
+ALTER TABLE recoveryKeys ADD COLUMN recoveryKeyIdHash BINARY(32),
+ALGORITHM = INPLACE, LOCK = NONE;
```
Comment (rfk) [inline lib/db/schema/patch-085-086.sql]: This table will still have a `recoveryKeyId` column, right?  We'll need a followup bug to drop that column in a subsequent migration.

If we're assuming that the `recoveryKeys` table is empty, it may be worth adding some logic here in the migration to ensure that - either by explicitly deleting any existing rows, or by erroring out if there are rows present.

File: lib/db/schema/patch-085-086.sql [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+
+  SET @accountCount = 0;
+
+  -- Signal error if no user found
+  SELECT COUNT(*) INTO @accountCount FROM `accounts` WHERE `uid` = `uidArg`;
+  IF @accountCount = 0 THEN
+    SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = 1643, MESSAGE_TEXT = 'Can not create recovery key for unknown user.';
+  END IF;
+
+  INSERT INTO recoveryKeys (uid, recoveryKeyIdHash, recoveryData) VALUES (uidArg, recoveryKeyIdHashArg, recoveryDataArg);
```
Comment (rfk) [inline lib/db/schema/patch-085-086.sql]: I'm surprised this works without also inserting a value for the `recoveryKeyId` field; what am I missing?

File: lib/db/schema/patch-085-086.sql (hunk 2 above)
Comment (vbudhram) [reply lib/db/schema/patch-085-086.sql]: > This table will still have a recoveryKeyId column, right?

It would but I guess since I would be deleting existing rows, I could remove the column in this migration as well.

File: lib/db/schema/patch-085-086.sql (hunk 3 above)
Comment (vbudhram) [reply lib/db/schema/patch-085-086.sql]: Hmm, looks like the `recoveryKeyId` column is allowed to be null (it probably shouldn't have been), which means I should make `recoveryKeyIdHash` NOT NULL.

**Comment by vbudhram** [comment]
@rfk Updated from your review. To support changes, I needed to expose a new endpoint `recoveryKeyExists` that doesn't take the `recoveryKeyId`.

@mozilla/fxa-devs r?

File: db-server/test/backend/db_tests.js [hunk 4]
```diff
@@ -2312,14 +2317,39 @@ module.exports = function (config, DB) {
...
+              .then((res) => {
+                assert.equal(res.exists, false, 'key exists')
+              })
+          })
+      })
+
+      it('should throw when checking for recovery key on non-existent user', () => {
+        return db.recoveryKeyExists('nonexistent')
+          .then((res) => {
+            assert.equal(res.exists, false, 'key exists')
```
Comment (rfk) [inline db-server/test/backend/db_tests.js]: nit: the message here should be "key does not exist" or similar.

File: db-server/test/backend/db_tests.js [hunk 5]
```diff
@@ -2312,14 +2317,39 @@ module.exports = function (config, DB) {
...
+          })
+      })
+
+      it('should return false if recovery key doesn\'t exist', () => {
+        account = createAccount()
+        return db.createAccount(account.uid, account)
+          .then(() => {
+            return db.recoveryKeyExists(account.uid)
+              .then((res) => {
+                assert.equal(res.exists, false, 'key exists')
```
Comment (rfk) [inline db-server/test/backend/db_tests.js]: nit: the message here should be "key does not exist" or similar.

File: docs/API.md [hunk 6]
```diff
@@ -2281,3 +2281,41 @@ Content-Length: 2
...
+HTTP/1.1 200 OK
+Content-Type: application/json
+Content-Length: 2
+
+{"exists": true}
+```
+
+* Status Code : `200 OK`
+    * Content-Type : `application/json`
+    * Body : `true`
```
Comment (rfk) [inline docs/API.md]: Seems like `Body` here should be `{exists: true}` or similar?

File: docs/DB_API.md [hunk 7]
```diff
@@ -952,16 +953,18 @@ Returns:
   * An empty object
 * Rejects with:
   * Any error from the underlying storage system (wrapped in `error.wrap()`)
-  * `error.notFound()` if this user found
+  * `error.notFound()` if this user foundgetRecoveryKey
```
Comment (rfk) [inline docs/DB_API.md]: "foundgetRecoveryKey"?

File: lib/db/schema/patch-085-086.sql [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+SET NAMES utf8mb4 COLLATE utf8mb4_bin;
+
+CALL assertPatchLevel('85');
+
+DELETE FROM recoveryKeys;
+
+-- We can drop this since we will be using the `recoveryKeyIdHash`
+-- column instead.
+ALTER TABLE recoveryKeys DROP COLUMN recoveryKeyId,
+ALGORITHM = INPLACE, LOCK = NONE;
```
Comment (rfk) [inline lib/db/schema/patch-085-086.sql]: If someone tries to add a recovery key while we're in the process of rolling this out, they might end up calling the old `createRecoveryKey_2` procedure, which will error out trying to access the now-removed `recoveryKeyId` column.

That's probably for the best (and is better than letting them insert a soon-to-not-be-working-correctly key`) but we should document it here explicitly to re-assure our friendly Ops folks that it's safe to drop this column :-)

File: lib/db/mem.js [hunk 9]
```diff
@@ -1389,10 +1390,39 @@ module.exports = function (log, error) {
           return P.reject(error.notFound())
         }
 
+        if (! dbUtil.buffersAreEqual(recoveryKey.recoveryKeyIdHash, recoveryKeyIdHash)) {
```
Comment (rfk) [inline lib/db/mem.js]: Aha, so, we actually don't need to do this constant-time-comparison stuff here.  We're comparing hashes rather than raw strings, and it doesn't matter if an attacker can harvest timing data about how close the two hashes are to matching.  We can just use the existing buffer-equality check.
