### PR TITLE
fix(performance): Add index for scanning signinCodes by uid.

### LINKED ISSUE #405: unindexed delete
I was looking at the slow query log on the read replica and this query shows up as taking an average of 0.75 seconds and scanning the table:
  `DELETE FROM signinCodes WHERE uid = X'...'`

There aren't an egregious number of rows in that table (compared to others), but perhaps it needs an index (either on the table, or if there's a way to use one of the indices that already exist).

For fun, I think adding an index for `uid` ***on the slave only*** would be interesting

### PR DESCRIPTION
**Pull request by rfk**
Fixes #405

### CODE REVIEW

File: lib/db/schema/patch-088-089.sql [hunk 1]
```diff
@@ -0,0 +1,11 @@
+-- Add an index to walk sininCodes table by uid,
```
Comment (philbooth) [inline lib/db/schema/patch-088-089.sql]: Typo: `signinCodes`.
