### PR TITLE
fix(db): don't return zombie devices from accountDevices

### LINKED ISSUE #162: Should we enforce device <=> sessionToken parity?
This question arises from discussion about the following query from #160 (later removed):

```sql
-- Prior to this migration, it was possible to delete a session token
-- without deleting the associated device (if a device record exists).
-- That's fixed by deleteSessionTokens_3, but we should also purge any
-- historical devices that have reached this state.
DELETE FROM devices
  USING devices LEFT JOIN sessionTokens
    ON devices.sessionTokenId = sessionTokens.tokenId
  WHERE sessionTokens.tokenId IS NULL;
```

Leaving aside the unresolved question of whether it is feasible to run against the production database, it is only worth doing if we can sanely enforce the existence of a session token for every device record.

Based on eyeballing the stored procedures and testing assorted connection and disconnection methods, I think we can enforce that. The related problem described in mozilla/fxa-content-server#4060 doesn't affect the parity because both the session token and the device are left in the database in that case.

Whether we want to enforce any parity is another matter. In addition to any cost of running the above query to delete zombies, there is the cost of adding a new constraint to the `devices` table in the production database. Hence opening this issue as a question.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #162.

Possibly this is wrong because I've ploughed the `INNER JOIN` furrow raised in https://github.com/mozilla/fxa-auth-db-mysql/issues/162#issuecomment-243435229, without waiting for feedback. I figured I may as well offer something concrete to discuss.

(and sorry about #164, ignore everything I said there!)

### CODE REVIEW

File: fxa-auth-db-server/test/backend/db_tests.js [hunk 1]
```diff
@@ -1208,6 +1211,36 @@ module.exports = function(config, DB) {
                 t.equal(device.callbackPublicKey, '', 'callbackPublicKey updated')
                 t.equal(device.callbackAuthKey, '', 'callbackAuthKey updated')
 
+                // Make the device a zombie, by giving it a non-existent session token
```
Comment (vbudhram) [inline fxa-auth-db-server/test/backend/db_tests.js]: @philbooth While I am not entirely sure how the zombie session gets created, would it make sense to have some checks to `updateDevice` to ensure session is valid before updating?

Comment (philbooth) [inline fxa-auth-db-server/test/backend/db_tests.js]: The zombies *were* created when session token's got deleted without the corresponding device also being deleted. That's how the `deleteSessionToken` and `resetAccount` stored procedures used to behave.

We've got no reason to believe that any zombie sessions have been created by passing a bogus session token id to `createDevice` or `updateDevice`. Which is not to say it would definitely be wrong to add some kind of check, but that would require an extra db query to be weighed against any perceived benefit. Essentially we trust the auth server to get stuff right.

So my instinct is it's not worth it, although I'm happy to be put right if there's something i'm missing.

Comment (vbudhram) [inline fxa-auth-db-server/test/backend/db_tests.js]: @philbooth That's fair, the effects of adding an extra lookup on this query is probably not worth all the hassle.

**Comment by rfk** [comment]
The approach seems reasonable to me

**Comment by philbooth** [comment]
@vbudhram, as you've already commented I'm tagging you for the official r?

File: fxa-auth-db-server/test/backend/db_tests.js [hunk 2]
```diff
@@ -1208,6 +1211,36 @@ module.exports = function(config, DB) {
...
+                .catch(function () {
+                  t.fail('updating an existing device should not have failed')
+                })
+              })
+              .then(function () {
+                // Fetch all of the devices for the account
+                return db.accountDevices(ACCOUNT.uid)
+              })
+              .then(function (devices) {
+                t.equal(devices.length, 0, 'devices is empty')
```
Comment (vbudhram) [inline fxa-auth-db-server/test/backend/db_tests.js]: Should we update the documentation for [accountDevices](https://github.com/mozilla/fxa-auth-db-mysql/blob/master/docs/API.md#accountdevicesuid) to mention that devices with zombie session wouldn't be returned.

**Comment by vbudhram** [comment]
@philbooth Not in the scope of this PR, but maybe something to think about, was how we were going to delete zombie sessions? Since they are not returned from `accountDevices` anymore, the only way I could see that happening is through a script?

Besides nits, LGTM 👍 , merge at will

File: fxa-auth-db-server/test/backend/db_tests.js (hunk 2 above)
Comment (philbooth) [inline fxa-auth-db-server/test/backend/db_tests.js]: I thought about that and decided against it because it would also require explaining what a zombie device is and why such a thing may exist in the first place, which seemed out of scope. It is not a concept that is referred to elsewhere in our docs so it felt weird to suddenly introduce it here.

**Comment by philbooth** [comment]
> Not in the scope of this PR, but maybe something to think about, was how we were going to delete zombie sessions?

I'm not even sure we will delete them. The precursor to all this was actually a [discussion](https://github.com/mozilla/fxa-auth-db-mysql/pull/160#discussion_r75235298) about such a `DELETE` query that was removed from an earlier migration due to performance concerns. This PR represents a conscious decision to avoid those concerns by just ignoring the zombies.

**Comment by philbooth** [comment]
Thanks @vbudhram! 👍
